[package_manager]
name = "dnf"
display_name = "DNF (Fedora/RHEL)"
executable = "dnf"
list_packages_cmd = "dnf list --available"
list_installed_cmd = "dnf list --installed"
search_cmd = "dnf search {}"
install_cmd = "dnf install {}"
requires_root = true
package_separator = " "
installed_indicator = "@"