[package_manager]
name = "nix"
display_name = "Nix (nixpkgs)"
executable = "nix-env"
search_cmd = "nix search nixpkgs {}"
install_cmd = "nix-env -iA nixpkgs.{}"
requires_root = false
package_separator = " "
installed_indicator = "*"