[package_manager]
name = "paru"
display_name = "Paru (AUR)"
executable = "paru"
list_packages_cmd = "paru -Slqa"
list_installed_cmd = "paru -Q"
search_cmd = "paru -Ss {}"
install_cmd = "paru -S {}"
requires_root = false
package_separator = " "
installed_indicator = "*"